// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250620132903_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BranchOffice", b =>
                {
                    b.Property<int>("BranchOfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchOfficeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("BranchOfficeZoneId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LocationReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BranchOfficeId");

                    b.HasIndex("BranchOfficeZoneId");

                    b.ToTable("BranchOffices", (string)null);

                    b.HasData(
                        new
                        {
                            BranchOfficeId = 1,
                            Address = "Av. Del Libertador 16500",
                            BranchOfficeZoneId = 1,
                            City = "San Isidro",
                            Hours = "08:00-18:00",
                            Latitude = -34.46659m,
                            LocationReference = "Cerca de la Plaza Mitre",
                            Longitude = -58.51120m,
                            Name = "Sucursal San Isidro",
                            Phone = "011-4747-2442",
                            PostalCode = "B1642",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 2,
                            Address = "Av. Maipú 1234",
                            BranchOfficeZoneId = 1,
                            City = "Vicente López",
                            Hours = "09:00-19:00",
                            Latitude = -34.52664m,
                            LocationReference = "Cerca de la estación Vicente López",
                            Longitude = -58.48269m,
                            Name = "Sucursal Vicente López",
                            Phone = "011-4791-1234",
                            PostalCode = "B1602",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 3,
                            Address = "Av. Maipú 2990",
                            BranchOfficeZoneId = 1,
                            City = "Olivos",
                            Hours = "08:00-20:00",
                            Latitude = -34.50828m,
                            LocationReference = "Junto a la Plaza Olivos",
                            Longitude = -58.49208m,
                            Name = "Sucursal Olivos",
                            Phone = "011-4795-1850",
                            PostalCode = "B1636",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 4,
                            Address = "Beruti 1660",
                            BranchOfficeZoneId = 1,
                            City = "Martínez",
                            Hours = "08:00-19:00",
                            Latitude = -34.49152m,
                            LocationReference = "Cerca de Plaza 9 de Julio",
                            Longitude = -58.51122m,
                            Name = "Sucursal Martínez",
                            Phone = "011-4734-3600",
                            PostalCode = "B1640",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 5,
                            Address = "Av. Rolón 2007",
                            BranchOfficeZoneId = 1,
                            City = "Boulogne",
                            Hours = "09:00-18:00",
                            Latitude = -34.50857m,
                            LocationReference = "Cerca del Shopping Los Arcos",
                            Longitude = -58.56605m,
                            Name = "Sucursal Boulogne",
                            Phone = "011-4749-4090",
                            PostalCode = "B1643",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 6,
                            Address = "Sarmiento 1249",
                            BranchOfficeZoneId = 1,
                            City = "San Fernando",
                            Hours = "08:00-17:00",
                            Latitude = -34.43997m,
                            LocationReference = "Frente a la Plaza Bartolome Mitre",
                            Longitude = -58.55864m,
                            Name = "Sucursal San Fernando",
                            Phone = "011-4743-0550",
                            PostalCode = "B1646",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 7,
                            Address = "Av. Italia 1398",
                            BranchOfficeZoneId = 1,
                            City = "Tigre",
                            Hours = "09:00-20:00",
                            Latitude = -34.42351m,
                            LocationReference = "A metros del Puerto de Frutos",
                            Longitude = -58.57615m,
                            Name = "Sucursal Tigre",
                            Phone = "011-4512-0550",
                            PostalCode = "B1648",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 8,
                            Address = "Carlos Francisco Melo 2501",
                            BranchOfficeZoneId = 1,
                            City = "Florida",
                            Hours = "08:00-19:00",
                            Latitude = -34.53501m,
                            LocationReference = "Cerca del Shopping Florida",
                            Longitude = -58.49238m,
                            Name = "Sucursal Florida",
                            Phone = "011-4794-1075",
                            PostalCode = "B1602",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 9,
                            Address = "Av. del Libertador 15089",
                            BranchOfficeZoneId = 1,
                            City = "Acassuso",
                            Hours = "09:00-19:00",
                            Latitude = -34.47526m,
                            LocationReference = "Cerca del Hipodromo de San Isidro",
                            Longitude = -58.49972m,
                            Name = "Sucursal Acassuso",
                            Phone = "011-4795-1450",
                            PostalCode = "B1641",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 10,
                            Address = "Av. Centenario 1920",
                            BranchOfficeZoneId = 1,
                            City = "Beccar",
                            Hours = "08:00-18:00",
                            Latitude = -34.46106m,
                            LocationReference = "Frente a la estacion Beccar",
                            Longitude = -58.52738m,
                            Name = "Sucursal Beccar",
                            Phone = "011-4794-1400",
                            PostalCode = "B1642",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 11,
                            Address = "Av. Mitre 500",
                            BranchOfficeZoneId = 2,
                            City = "Quilmes",
                            Hours = "08:00-20:00",
                            Latitude = -34.7206m,
                            LocationReference = "Frente a la estación Quilmes",
                            Longitude = -58.2673m,
                            Name = "Sucursal Quilmes",
                            Phone = "011-4257-0500",
                            PostalCode = "B1878",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 12,
                            Address = "Av. Yrigoyen 700",
                            BranchOfficeZoneId = 2,
                            City = "Lomas de Zamora",
                            Hours = "09:00-19:00",
                            Latitude = -34.7620m,
                            LocationReference = "Esquina con Camino Negro",
                            Longitude = -58.3950m,
                            Name = "Sucursal Lomas de Zamora",
                            Phone = "011-4220-0700",
                            PostalCode = "B1832",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 13,
                            Address = "Av. Alsina 300",
                            BranchOfficeZoneId = 2,
                            City = "Banfield",
                            Hours = "08:00-18:00",
                            Latitude = -34.7907m,
                            LocationReference = "Frente a la estación Banfield",
                            Longitude = -58.3958m,
                            Name = "Sucursal Banfield",
                            Phone = "011-4240-0300",
                            PostalCode = "B1828",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 14,
                            Address = "Av. Belgrano 100",
                            BranchOfficeZoneId = 2,
                            City = "Avellaneda",
                            Hours = "09:00-20:00",
                            Latitude = -34.6559m,
                            LocationReference = "Cerca del Puente Pueyrredón",
                            Longitude = -58.3645m,
                            Name = "Sucursal Avellaneda",
                            Phone = "011-4227-0100",
                            PostalCode = "B1870",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 15,
                            Address = "Av. 9 de Julio 2500",
                            BranchOfficeZoneId = 2,
                            City = "Lanús",
                            Hours = "08:00-19:00",
                            Latitude = -34.7025m,
                            LocationReference = "A metros de la estación Lanús",
                            Longitude = -58.3794m,
                            Name = "Sucursal Lanús",
                            Phone = "011-4243-2500",
                            PostalCode = "B1824",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 16,
                            Address = "Av. Mitre 2100",
                            BranchOfficeZoneId = 2,
                            City = "Berazategui",
                            Hours = "09:00-18:00",
                            Latitude = -34.8282m,
                            LocationReference = "Esquina con calle 14",
                            Longitude = -58.2165m,
                            Name = "Sucursal Berazategui",
                            Phone = "011-4212-2100",
                            PostalCode = "B1884",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 17,
                            Address = "Av. Hudson 1900",
                            BranchOfficeZoneId = 2,
                            City = "Florencio Varela",
                            Hours = "08:00-17:00",
                            Latitude = -34.8290m,
                            LocationReference = "Frente al Shopping Varela",
                            Longitude = -58.2780m,
                            Name = "Sucursal Florencio Varela",
                            Phone = "011-4211-1900",
                            PostalCode = "B1888",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 18,
                            Address = "Av. Espora 4200",
                            BranchOfficeZoneId = 2,
                            City = "Almirante Brown",
                            Hours = "09:00-19:00",
                            Latitude = -34.7840m,
                            LocationReference = "Junto a la Plaza Brown",
                            Longitude = -58.3895m,
                            Name = "Sucursal Almirante Brown",
                            Phone = "011-4260-4200",
                            PostalCode = "B1847",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 19,
                            Address = "Av. Pedro Buratovich 150",
                            BranchOfficeZoneId = 2,
                            City = "San Vicente",
                            Hours = "08:00-18:00",
                            Latitude = -34.8650m,
                            LocationReference = "A metros del Hospital",
                            Longitude = -58.4052m,
                            Name = "Sucursal San Vicente",
                            Phone = "011-4295-0150",
                            PostalCode = "B1865",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 20,
                            Address = "Av. Brown 1500",
                            BranchOfficeZoneId = 2,
                            City = "Esteban Echeverría",
                            Hours = "09:00-20:00",
                            Latitude = -34.8080m,
                            LocationReference = "Frente a la Municipalidad",
                            Longitude = -58.4590m,
                            Name = "Sucursal Esteban Echeverría",
                            Phone = "011-4296-1500",
                            PostalCode = "B1842",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 21,
                            Address = "Av. Rivadavia 100",
                            BranchOfficeZoneId = 3,
                            City = "Morón",
                            Hours = "08:00-20:00",
                            Latitude = -34.6500m,
                            LocationReference = "Cerca de la estación Morón",
                            Longitude = -58.6200m,
                            Name = "Sucursal Morón",
                            Phone = "011-4650-0100",
                            PostalCode = "B1708",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 22,
                            Address = "Av. Libertador 200",
                            BranchOfficeZoneId = 3,
                            City = "Merlo",
                            Hours = "09:00-19:00",
                            Latitude = -34.6520m,
                            LocationReference = "Frente al Municipio de Merlo",
                            Longitude = -58.7060m,
                            Name = "Sucursal Merlo",
                            Phone = "011-4660-0200",
                            PostalCode = "B1722",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 23,
                            Address = "Av. Eva Perón 800",
                            BranchOfficeZoneId = 3,
                            City = "Moreno",
                            Hours = "08:00-18:00",
                            Latitude = -34.6475m,
                            LocationReference = "A metros de la plaza central",
                            Longitude = -58.6192m,
                            Name = "Sucursal Moreno",
                            Phone = "011-4628-0800",
                            PostalCode = "B1744",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 24,
                            Address = "Av. Rivadavia 8500",
                            BranchOfficeZoneId = 3,
                            City = "Ituzaingó",
                            Hours = "09:00-20:00",
                            Latitude = -34.6574m,
                            LocationReference = "Frente al Puente 12",
                            Longitude = -58.7035m,
                            Name = "Sucursal Ituzaingó",
                            Phone = "011-4620-8500",
                            PostalCode = "B1714",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 25,
                            Address = "Av. Vergara 500",
                            BranchOfficeZoneId = 3,
                            City = "Hurlingham",
                            Hours = "08:00-19:00",
                            Latitude = -34.6083m,
                            LocationReference = "Cerca del Club Hurlingham",
                            Longitude = -58.6150m,
                            Name = "Sucursal Hurlingham",
                            Phone = "011-4617-0500",
                            PostalCode = "B1686",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 26,
                            Address = "Av. San Martín 2400",
                            BranchOfficeZoneId = 3,
                            City = "Tres de Febrero",
                            Hours = "09:00-19:00",
                            Latitude = -34.6394m,
                            LocationReference = "Frente al shopping Tres de Febrero",
                            Longitude = -58.6477m,
                            Name = "Sucursal Tres de Febrero",
                            Phone = "011-4625-2400",
                            PostalCode = "B1678",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 27,
                            Address = "Av. Vte. López y Planes 600",
                            BranchOfficeZoneId = 3,
                            City = "San Justo",
                            Hours = "08:00-18:00",
                            Latitude = -34.6946m,
                            LocationReference = "Cerca del Hospital San Justo",
                            Longitude = -58.5449m,
                            Name = "Sucursal San Justo",
                            Phone = "011-4254-0600",
                            PostalCode = "B1754",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 28,
                            Address = "Av. San Martín 2500",
                            BranchOfficeZoneId = 3,
                            City = "Caseros",
                            Hours = "09:00-20:00",
                            Latitude = -34.6313m,
                            LocationReference = "Frente a la estación Caseros",
                            Longitude = -58.5503m,
                            Name = "Sucursal Caseros",
                            Phone = "011-4624-2500",
                            PostalCode = "B1678",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 29,
                            Address = "Av. Eva Perón 3450",
                            BranchOfficeZoneId = 3,
                            City = "Rafael Castillo",
                            Hours = "08:00-19:00",
                            Latitude = -34.6983m,
                            LocationReference = "A metros del Club Ferrocarril Oeste",
                            Longitude = -58.6180m,
                            Name = "Sucursal Rafael Castillo",
                            Phone = "011-4256-3450",
                            PostalCode = "B1758",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 30,
                            Address = "Av. Presidente Perón 2000",
                            BranchOfficeZoneId = 3,
                            City = "Ciudad Evita",
                            Hours = "09:00-18:00",
                            Latitude = -34.7000m,
                            LocationReference = "Junto a la Plaza Evita",
                            Longitude = -58.5010m,
                            Name = "Sucursal Ciudad Evita",
                            Phone = "011-4253-2000",
                            PostalCode = "B1753",
                            Province = "Buenos Aires"
                        },
                        new
                        {
                            BranchOfficeId = 31,
                            Address = "Rivadavia 100",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "09:00-17:00",
                            Latitude = -34.6082m,
                            LocationReference = "Frente a Casa Rosada",
                            Longitude = -58.3738m,
                            Name = "Sucursal Plaza de Mayo",
                            Phone = "011-4370-0100",
                            PostalCode = "C1084",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 32,
                            Address = "Av. Dr. J. M. Ramos Mejía 777",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "08:00-20:00",
                            Latitude = -34.5882m,
                            LocationReference = "Frente a la estación Retiro",
                            Longitude = -58.3744m,
                            Name = "Sucursal Retiro",
                            Phone = "011-4379-0777",
                            PostalCode = "C1061",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 33,
                            Address = "Av. Santa Fe 3200",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "09:00-21:00",
                            Latitude = -34.5891m,
                            LocationReference = "Esquina con Bulnes",
                            Longitude = -58.4245m,
                            Name = "Sucursal Palermo",
                            Phone = "011-4833-3200",
                            PostalCode = "C1425",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 34,
                            Address = "Junín 1800",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "08:00-20:00",
                            Latitude = -34.5884m,
                            LocationReference = "Cerca del Cementerio",
                            Longitude = -58.3910m,
                            Name = "Sucursal Recoleta",
                            Phone = "011-4808-1800",
                            PostalCode = "C1113",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 35,
                            Address = "Av. Cabildo 2200",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "09:00-19:00",
                            Latitude = -34.5570m,
                            LocationReference = "Frente a la estación Belgrano R",
                            Longitude = -58.4478m,
                            Name = "Sucursal Belgrano",
                            Phone = "011-4714-2200",
                            PostalCode = "C1426",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 36,
                            Address = "Defensa 700",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "09:00-18:00",
                            Latitude = -34.6195m,
                            LocationReference = "A metros de Plaza Dorrego",
                            Longitude = -58.3733m,
                            Name = "Sucursal San Telmo",
                            Phone = "011-4294-0700",
                            PostalCode = "C1065",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 37,
                            Address = "Caminito 415",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "10:00-18:00",
                            Latitude = -34.6347m,
                            LocationReference = "Junto al Puente de la Mujer",
                            Longitude = -58.3633m,
                            Name = "Sucursal La Boca",
                            Phone = "011-4302-0415",
                            PostalCode = "C1164",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 38,
                            Address = "Florida 300",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "08:00-22:00",
                            Latitude = -34.6083m,
                            LocationReference = "A una cuadra de Av. Corrientes",
                            Longitude = -58.3707m,
                            Name = "Sucursal Microcentro",
                            Phone = "011-4331-0300",
                            PostalCode = "C1005",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 39,
                            Address = "Av. Corrientes 3800",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "09:00-20:00",
                            Latitude = -34.6050m,
                            LocationReference = "Frente al teatro",
                            Longitude = -58.4185m,
                            Name = "Sucursal Almagro",
                            Phone = "011-4951-3800",
                            PostalCode = "C1182",
                            Province = "CABA"
                        },
                        new
                        {
                            BranchOfficeId = 40,
                            Address = "Av. del Libertador 7766",
                            BranchOfficeZoneId = 4,
                            City = "Ciudad Autónoma de Buenos Aires",
                            Hours = "09:00-21:00",
                            Latitude = -34.54300m,
                            LocationReference = "Cerca del CeNARD",
                            Longitude = -58.46186m,
                            Name = "Sucursal Núñez",
                            Phone = "011-4784-4500",
                            PostalCode = "C1428",
                            Province = "CABA"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BranchOfficeZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zona Norte"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zona Sur"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zona Oeste"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Capital Federal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Interior del País"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("TransmissionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Automático"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleStatusId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("BranchOfficeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransmissionTypeId");

                    b.HasIndex("VehicleStatusId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("VehicleCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vehículo de tamaño mediano, ideal para uso familiar o personal, con un diseño cerrado y cómodo.",
                            Name = "Sedán"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vehículo utilitario deportivo, con mayor espacio y capacidad para terrenos difíciles.",
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vehículo compacto con una puerta trasera que da acceso al baúl, ideal para la ciudad.",
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vehículo con una cabina y una zona de carga abierta, ideal para transporte de mercancías.",
                            Name = "Pickup"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vehículo diseñado para altas prestaciones, con un diseño aerodinámico y potente.",
                            Name = "Deportivo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vehículo de dos puertas con un diseño elegante y deportivo, ideal para uso personal.",
                            Name = "Coupé"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ideal para familias grandes o grupos.",
                            Name = "Minivan"
                        });
                });

            modelBuilder.Entity("Domain.Entities.VehicleDocument", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleDocuments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleReviews", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VehicleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("VehicleStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Disponible"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ocupado"
                        },
                        new
                        {
                            Id = 3,
                            Name = "En Mantenimiento"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BranchOffice", b =>
                {
                    b.HasOne("Domain.Entities.BranchOfficeZone", "Zone")
                        .WithMany("BranchOffices")
                        .HasForeignKey("BranchOfficeZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("Domain.Entities.BranchOffice", "BranchOffice")
                        .WithMany("Vehicles")
                        .HasForeignKey("BranchOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VehicleCategory", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TransmissionType", "TransmissionType")
                        .WithMany("Vehicles")
                        .HasForeignKey("TransmissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VehicleStatus", "VehicleStatus")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchOffice");

                    b.Navigation("Category");

                    b.Navigation("TransmissionType");

                    b.Navigation("VehicleStatus");
                });

            modelBuilder.Entity("Domain.Entities.VehicleDocument", b =>
                {
                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Documents")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.VehicleReview", b =>
                {
                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Reviews")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.BranchOffice", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Domain.Entities.BranchOfficeZone", b =>
                {
                    b.Navigation("BranchOffices");
                });

            modelBuilder.Entity("Domain.Entities.TransmissionType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.VehicleCategory", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Domain.Entities.VehicleStatus", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
